name: certeasy-no-publish

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:

  pull_request:
    paths:
      - 'certeasy-core/**'
      - 'certeasy-bouncycastle/**'
      - 'certeasy-backend-app/**'
      - '.github/workflows/certeasy-no-publish.yaml'

  push:
    paths:
      - 'certeasy-core/**'
      - 'certeasy-bouncycastle/**'
      - 'certeasy-backend-app/**'
      - '.github/workflows/certeasy-no-publish.yaml'
    branches-ignore:
      - main
      - develop

jobs:

  build-core:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./certeasy-core
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        name: Git checkout
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Maven build
        run: mvn --batch-mode package install -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=certeasy-core
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_CORE_TOKEN }}
      - name: Upload certeasy-core
        uses: actions/upload-artifact@v2
        with:
          name: certeasy-core
          path: ~/.m2/repository/org/certeasy/certeasy-core

  build-bouncycastle:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./certeasy-bouncycastle
    permissions:
      contents: read
      packages: write
    needs: ["build-core"]
    steps:
      - uses: actions/checkout@v3
        name: Git checkout
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Download certeasy-core
        uses: actions/download-artifact@v2
        with:
          name: certeasy-core
          path: ~/.m2/repository/org/certeasy/certeasy-core
      - name: Maven build
        run: mvn --batch-mode package install -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=certeasy-bouncycastle
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_BOUNCYCASTLE_TOKEN }}
      - name: Upload certeasy-bouncycastle
        uses: actions/upload-artifact@v2
        with:
          name: certeasy-bouncycastle
          path: ~/.m2/repository/org/certeasy/certeasy-bouncycastle

  build-binary:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: ./certeasy-backend-app
    needs: ["build-core", "build-bouncycastle"]
    steps:
      - uses: actions/checkout@v3
        name: Git checkout
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Download certeasy-core
        uses: actions/download-artifact@v2
        with:
          name: certeasy-core
          path: ~/.m2/repository/org/certeasy/certeasy-core
      - name: Download bouncycastle
        uses: actions/download-artifact@v2
        with:
          name: certeasy-bouncycastle
          path: ~/.m2/repository/org/certeasy/certeasy-bouncycastle
      - name: Maven build
        run: mvn --batch-mode package -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=certeasy-backend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_BACKEND_TOKEN }}
      - name: Build binary
        run: |
          ./mvnw package -Pnative -Dquarkus.native.container-build=true
      - name: Upload certeasy-binary
        uses: actions/upload-artifact@v2
        with:
          name: certeasy-binary
          path: ./target/certeasy-bke

  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: ["build-binary"]
    steps:
      - uses: actions/checkout@v3
        name: Git checkout
      - name: Download certeasy-binary
        uses: actions/download-artifact@v2
        with:
          name: certeasy-binary
          path: ./
      - name: Registry login
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Image metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Image build and push
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:test
          labels: ${{ steps.meta.outputs.labels }}
