name: certeasy-bouncycastle

defaults:
 run:
  working-directory: ./certeasy-bouncycastle

on:

  workflow_run:
    workflows: [ "certeasy-core" ]
    types:
      - completed

  push:
    paths-ignore:
      - 'certeasy-core/**'
      - 'certeasy-backend-app/**'

  pull_request:
    paths-ignore:
      - 'certeasy-core/**'
      - 'certeasy-backend-app/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        name: Git checkout
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Maven build
        run: mvn --batch-mode package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Maven deploy
        run: mvn --batch-mode deploy
        if: ${{ github.event_name != 'pull_request' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
