name: certeasy-restful

defaults:
 run:
  working-directory: ./certeasy-restful

on: [push, pull_request]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        name: Git checkout
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Maven build
        run: mvn --batch-mode package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Quarkus native build
        run: ./mvnw package -Pnative -Dquarkus.native.container-build=true -Dproject.build.finalName=certeasy
      
