name: certeasy-image

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:

  push:
    paths:
      - 'certeasy-core/**'
      - 'certeasy-bouncycastle/**'
      - 'certeasy-backend-app/**'
      - '.github/workflows/certeasy.yaml'

  pull_request:
    paths:
      - 'certeasy-core/**'
      - 'certeasy-bouncycastle/**'
      - 'certeasy-backend-app/**'
      - '.github/workflows/certeasy.yaml'

jobs:

  certeasy-core:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./certeasy-core
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        name: Git checkout
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Maven build
        run: mvn --batch-mode package -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=certeasy-core
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_CORE_TOKEN }}
      - name: Maven deploy
        run: mvn --batch-mode deploy
        if: ${{ github.event_name != 'pull_request' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  certeasy-bouncycastle:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./certeasy-bouncycastle
    permissions:
      contents: read
      packages: write
    needs: ["certeasy-core"]
    steps:
      - uses: actions/checkout@v3
        name: Git checkout
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Maven build
        run: mvn --batch-mode package -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=certeasy-bouncycastle
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_BOUNCYCASTLE_TOKEN }}
      - name: Maven deploy
        run: mvn --batch-mode deploy
        if: ${{ github.event_name != 'pull_request' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  certeasy-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: ./certeasy-backend-app
    needs: ["certeasy-core", "certeasy-bouncycastle"]
    steps:
      - uses: actions/checkout@v3
        name: Git checkout
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Maven build
        run: mvn --batch-mode package -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=certeasy-backend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_BACKEND_TOKEN }}
      - name: Build binary
        run: |
          ./mvnw package -Pnative -Dquarkus.native.container-build=true
      - name: Registry login
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Image metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Image build and push
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        if: ${{ github.event_name != 'pull_request' }}
        with:
          context: ./certeasy-backend-app
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

