name: certeasy-backend-app

defaults:
 run:
  working-directory: ./certeasy-restful

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on: 
  push:
    paths:
      - 'certeasy-backend-app/**'
      - '.github/workflows/certeasy-backend-app.yaml'

  pull_request:
    paths:
      - 'certeasy-backend-app/**'
      - '.github/workflows/certeasy-backend-app.yaml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        name: Git checkout
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Maven build
        run: mvn --batch-mode package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build binary
        run: |
          ./mvnw package -Pnative -Dquarkus.native.container-build=true
          ls -la ./target
      - name: Registry login
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Image metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Image build and push
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        if: ${{ github.event_name != 'pull_request' }}
        with:
          context: ./certeasy-backend-app
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
